name:                adventofcode2025
version:             0.1.0.0
github:              "liontiger23/adventofcode2025"
license:             BSD-3-Clause
author:              "Ivan Trepakov"
maintainer:          "liontiger23@gmail.com"
copyright:           "Copyright (c) 2025 Ivan Trepakov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/liontiger23/adventofcode2025#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- mtl
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  adventofcode2025-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode2025

tests:
  adventofcode2025-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode2025
